env = Environment(CCFLAGS = '-ggdb -pipe -Wall -O3 -ffast-math -Wno-unused -fPIC -DEMU', CFLAGS = '-std=gnu99')

env.Append(CPPPATH = ['../core'])

source = ['../core/bbcore.c','src/noisegen.cpp']
env.Program(source = source, target = "noisegen")



